-- CONFIG FOR MY BUILD OF CODEX

-- REQUIRE MAIN FILE

-- THE MAIN.LUA FILE ALREADY REQUIRES THIS CONFIG ASSUMING IT IS IN THE SRC DIRECTORY OF CODEX,
-- SO YOU DO NOT NEED TO REQUIRE IT FROM HERE UNLESS IT DOES NOT ALREADY REQUIRE IT FROM THERE.

-- CONFIG START

system.version = '1.3s'; -- SET THE SYSTEM VERSION IT DISPLAYS
system.file_bytes = 13075; -- SET FILE_BYTES FOR DIAGNOSTIC
